# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Density extraction 
NULL

quantileCpp <- function(x, q) {
    .Call('_rovquantR_quantileCpp', PACKAGE = 'rovquantR', x, q)
}

fastIntMode <- function(x, narm = FALSE) {
    .Call('_rovquantR_fastIntMode', PACKAGE = 'rovquantR', x, narm)
}

extractUniquePositiveValues <- function(matrix) {
    .Call('_rovquantR_extractUniquePositiveValues', PACKAGE = 'rovquantR', matrix)
}

createTransitionMatrix <- function(values) {
    .Call('_rovquantR_createTransitionMatrix', PACKAGE = 'rovquantR', values)
}

GetDensity <- function(sx, sy, z, IDmx, aliveStates, regionID, probs = as.numeric( c(0.025,0.975)), display_progress = TRUE, returnPosteriorCells = TRUE) {
    .Call('_rovquantR_GetDensity', PACKAGE = 'rovquantR', sx, sy, z, IDmx, aliveStates, regionID, probs, display_progress, returnPosteriorCells)
}

GetSpaceUse <- function(sx, sy, z, sigma, habitatxy, aliveStates, regionID, probs = as.numeric( c(0.025,0.975)), display_progress = TRUE, returnPosteriorCells = TRUE) {
    .Call('_rovquantR_GetSpaceUse', PACKAGE = 'rovquantR', sx, sy, z, sigma, habitatxy, aliveStates, regionID, probs, display_progress, returnPosteriorCells)
}

GetDetectability_normal <- function(p0, sigma, habitatxy, detectorxy, regionID, probs = as.numeric( c(0.025,0.975)), localDist = 100, display_progress = TRUE, returnPosteriorCells = FALSE) {
    .Call('_rovquantR_GetDetectability_normal', PACKAGE = 'rovquantR', p0, sigma, habitatxy, detectorxy, regionID, probs, localDist, display_progress, returnPosteriorCells)
}

GetDetectability_mean <- function(p0, sigma, habitatxy, detectorxy, display_progress = TRUE) {
    .Call('_rovquantR_GetDetectability_mean', PACKAGE = 'rovquantR', p0, sigma, habitatxy, detectorxy, display_progress)
}

GetTransitions <- function(sx1, sy1, z1, sx2, sy2, z2, stateFrom, stateTo, rgmx, probs = as.numeric( c(0.025,0.975)), display_progress = TRUE) {
    .Call('_rovquantR_GetTransitions', PACKAGE = 'rovquantR', sx1, sy1, z1, sx2, sy2, z2, stateFrom, stateTo, rgmx, probs, display_progress)
}

