# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' MCMC output post-processing
#' 
#' This set of \code{C++} functions are meant to facilitate the post-processing of SCR and OPSCR posterior samples in order to provide relevant information and derived quantities.
#' 
#' The \code{GetDensity} function extracts density estimates for a set of grid cells based on individual posterior activity center locations.
#' The \code{GetSpaceUse} function extracts density estimates for a set of grid cells based on individual posterior space use distribution.
#' The \code{GetDetectability_normal} function calculates detectability, i.e. the probability for an individual to be detected at least once for a set of grid cells based on posterior baseline detection probabilities and scale parameters. This function assumes a half-normal detection function.
#' The \code{GetDetectability_mean} function is a fast alternative of the \code{GetDetectability_normal} based on the posterior means of the parameters instead of the full posterior MCMC.
#' 
#' @param sx A numeric matrix containing posterior samples of individual activity center's x-coordinates.
#' @param sy A numeric matrix containing posterior samples of individual activity center's x-coordinates.
#' @param z A numeric matrix containing posterior samples of individual states.
#' @param sigma A numeric matrix containing posterior samples of individual sigma values.
#' @param p0 A numeric matrix containing posterior samples of individual baseline detection probabilities.
#' @param IDmx A numeric matrix containing the IDs of the habitat cells.
#' @param habitatxy A numeric matrix containing the coordinates of all habitat cells.
#' @param detectorxy A numeric matrix containing the coordinates of all detectors.
#' @param aliveStates A numeric vector of the alive states.
#' @param regionID  A binary matrix with dimensions (number of regions)*(number of habitat cells), denoting whether a given cell belongs the region (1) or not (0).
#' @param probs numeric vector with the values of the quantiles to be returned for the confidence interval.
#' @param display_progress A logical, whether to display progress bar or not.
#' @param returnPosteriorCells A logical, whether to return posterior values for each cell or not.
#' @param x A numeric vector whose sample quantiles (\code{quantileCpp}) or mode (\code{fastIntMode}) are wanted.
#' @param q A numeric vector with the values of the quantiles to be returned.
#' @param narm A logical, whether to remove NA values before calculation or not.
#' @param matrix A numeric matrix
#' @param values A numeric vector
#' @param localDist A numeric value
#' @param sx1,sx2,sy1,sy2 Numeric matrices of posterior x- and y-coordinates.
#' @param z1,z2 Numeric matrices of posterior x- and y-coordinates.
#' @param stateFrom,stateTo departure and arrival states.
#' @param rgmx A numeric matrix
#' 
#' @return Return_Description
#' 
#' @name GetDensity
quantileCpp <- function(x, q) {
    .Call('_rovquantR_quantileCpp', PACKAGE = 'rovquantR', x, q)
}

#' @rdname GetDensity
fastIntMode <- function(x, narm = FALSE) {
    .Call('_rovquantR_fastIntMode', PACKAGE = 'rovquantR', x, narm)
}

#' @rdname GetDensity
extractUniquePositiveValues <- function(matrix) {
    .Call('_rovquantR_extractUniquePositiveValues', PACKAGE = 'rovquantR', matrix)
}

#' @rdname GetDensity
createTransitionMatrix <- function(values) {
    .Call('_rovquantR_createTransitionMatrix', PACKAGE = 'rovquantR', values)
}

#' @rdname GetDensity
#' @export
GetDensity <- function(sx, sy, z, IDmx, aliveStates, regionID, probs = as.numeric( c(0.025,0.975)), display_progress = TRUE, returnPosteriorCells = TRUE) {
    .Call('_rovquantR_GetDensity', PACKAGE = 'rovquantR', sx, sy, z, IDmx, aliveStates, regionID, probs, display_progress, returnPosteriorCells)
}

#' @rdname GetDensity
#' @export
GetSpaceUse <- function(sx, sy, z, sigma, habitatxy, aliveStates, regionID, probs = as.numeric( c(0.025,0.975)), display_progress = TRUE, returnPosteriorCells = TRUE) {
    .Call('_rovquantR_GetSpaceUse', PACKAGE = 'rovquantR', sx, sy, z, sigma, habitatxy, aliveStates, regionID, probs, display_progress, returnPosteriorCells)
}

#' @rdname GetDensity
#' @export
GetDetectability_normal <- function(p0, sigma, habitatxy, detectorxy, regionID, probs = as.numeric( c(0.025,0.975)), localDist = 100, display_progress = TRUE, returnPosteriorCells = FALSE) {
    .Call('_rovquantR_GetDetectability_normal', PACKAGE = 'rovquantR', p0, sigma, habitatxy, detectorxy, regionID, probs, localDist, display_progress, returnPosteriorCells)
}

#' @rdname GetDensity
#' @export
GetDetectability_mean <- function(p0, sigma, habitatxy, detectorxy, display_progress = TRUE) {
    .Call('_rovquantR_GetDetectability_mean', PACKAGE = 'rovquantR', p0, sigma, habitatxy, detectorxy, display_progress)
}

#' @rdname GetDensity
#' @export
GetTransitions <- function(sx1, sy1, z1, sx2, sy2, z2, stateFrom, stateTo, rgmx, probs = as.numeric( c(0.025,0.975)), display_progress = TRUE) {
    .Call('_rovquantR_GetTransitions', PACKAGE = 'rovquantR', sx1, sy1, z1, sx2, sy2, z2, stateFrom, stateTo, rgmx, probs, display_progress)
}

